// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
// To validate version number use https://prantlf.github.io/build-number-generator/
const VERSION = '0.1.0.240620436';
export default VERSION;