import moment from 'moment';
import { numberToCurrencyFormat } from 'views/shared/BudgetSegment';
export const getCampaignDashRes = {
  statusCode: 200,
  statusDescription: ' Success. ',
  json: [
    {
      id: 2,
      name: "Marco Hernandez A's Campaigns",
      userId: 5,
      platformId: 0,
    },
    {
      id: 3,
      name: "Christopher Caruso's Campaigns",
      userId: 2,
      platformId: 0,
    },
    {
      id: 4,
      name: "Bode Lee's Campaigns",
      userId: 3,
      platformId: 0,
    },
    {
      id: 5,
      name: "Juan Carlos Chaves Barquero's Campaigns",
      userId: 4,
      platformId: 0,
    },
    {
      id: 6,
      name: "Boris Javier Monge Chaves's Campaigns",
      userId: 6,
      platformId: 0,
    },
    {
      id: 7,
      name: "Danny Jose Paco Guevara's Campaigns",
      userId: 7,
      platformId: 0,
    },
    {
      id: 8,
      name: "David Lopez's Campaigns",
      userId: 8,
      platformId: 0,
    },
    {
      id: 9,
      name: "Raj Kumar Kushwaha's Campaigns",
      userId: 9,
      platformId: 0,
    },
    {
      id: 10,
      name: "Uzma Idrees's Campaigns",
      userId: 10,
      platformId: 0,
    },
    {
      id: 11,
      name: "Gayatri Sanjay Kaley's Campaigns",
      userId: 11,
      platformId: 0,
    },
    {
      id: 12,
      name: "Kruti Kalpeshkumar Gandhi's Campaigns",
      userId: 12,
      platformId: 0,
    },
    {
      id: 13,
      name: "Riya Shetty's Campaigns",
      userId: 13,
      platformId: 0,
    },
    {
      id: 14,
      name: "Rajeev Kizhakke Palleeri's Campaigns",
      userId: 14,
      platformId: 0,
    },
    {
      id: 15,
      name: "David Urban's Campaigns",
      userId: 15,
      platformId: 0,
    },
    {
      id: 16,
      name: "Kendall Andrey Diaz Esquivel's Campaigns",
      userId: 16,
      platformId: 0,
    },
    {
      id: 17,
      name: "Sneha Chandrakant Powar's Campaigns",
      userId: 17,
      platformId: 0,
    },
    {
      id: 18,
      name: "Arpita Vinod Bhalerao's Campaigns",
      userId: 18,
      platformId: 0,
    },
    {
      id: 19,
      name: "Subasri Palanivel's Campaigns",
      userId: 19,
      platformId: 0,
    },
    {
      id: 20,
      name: "AppScanning Primary's Campaigns",
      userId: 20,
      platformId: 0,
    },
    {
      id: 21,
      name: "A56280DS_NPMHAuto's Campaigns",
      userId: 21,
      platformId: 0,
    },
    {
      id: 22,
      name: "T126138.01.test's Campaigns",
      userId: 22,
      platformId: 0,
    },
  ],
};

export const getUserManagementRes = {
  statusCode: 200,
  statusDescription: ' Success. ',
  json: [
    {
      id: 44,
      email: 'a56280dirnautomation@ds.dev.accenture.com',
      isActive: true,
      name: '',
      userRoleList: [
        {
          roleId: 5,
          roleName: 'Manager',
        },
      ],
      userAbilitiesList: [
        {
          abilityId: 7,
          abilityName: 'Recommendations Engine',
        },
        {
          abilityId: 1,
          abilityName: 'Ad Scheduling',
        },
      ],
    },
    {
      id: 21,
      email: 'A56280DS_NPMHAuto@ds.dev.accenture.com',
      isActive: true,
      name: '',
      userRoleList: [
        {
          roleId: 1,
          roleName: 'SuperAdmin',
        },
      ],
      userAbilitiesList: [
        {
          abilityId: 7,
          abilityName: 'Recommendations Engine',
        },
        {
          abilityId: 1,
          abilityName: 'Ad Scheduling',
        },
      ],
    },
  ],
};

export const userRes = {
  statusCode: 200,
  statusDescription: ' Success. ',
  json: {
    id: 13,
    email: 'riya.r.shetty@ds.dev.accenture.com',
    isActive: true,
    name: 'Raghunath Shetty, Riya',
    userRoleList: [
      {
        roleId: 1,
        roleName: 'SuperAdmin',
      },
    ],
    userAbilitiesList: [],
  },
};

export const getColumnsInfoRes = {
  statusCode: 200,
  statusDescription: ' Success. ',
  json: [
    {
      columns: [
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'campaign_name',
          value:
            'Active Shopper | Evergreen Model Support | DCP | BHT | CX-30 | FY158 | FI | Conversions | AMJ June - Evergreen - HEC - In-Feed',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'status',
          value: 'ACTIVE',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'free_text_reporting',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'free_text_launch_doc_url',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'lifetime_spend',
          value: '110953.85',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'pacing_budget_lifetime',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'pacing_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'budget_progress_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'free_text_pacing',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'pacing_budget_lifetime_start_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'pacing_budget_lifetime_end_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'account',
          value: 'Accenture - GTM / Mazda FY155-FY157',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'publisher_budget_media',
          value: '24972221',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 3,
          campaignKey: '23855136981530209',
          campaignDashColumnKey: 'pacing_budget_current_segment',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
      ],
    },
    {
      columns: [
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'campaign_name',
          value: 'C1176 Test Campaign do not remove',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'status',
          value: 'ACTIVE',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'free_text_reporting',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'free_text_launch_doc_url',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'lifetime_spend',
          value: '0',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'pacing_budget_lifetime',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'pacing_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'budget_progress_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'free_text_pacing',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'pacing_budget_lifetime_start_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'pacing_budget_lifetime_end_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'account',
          value: 'Accenture Automation Tests',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'publisher_budget_media',
          value: '1000000',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 1,
          campaignKey: '6094429360798',
          campaignDashColumnKey: 'pacing_budget_current_segment',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
      ],
    },
    {
      columns: [
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'campaign_name',
          value:
            'Active Shopper | Evergreen Model Support | DCP | BHT | CX-5 | FY158 | FI | Conversions | AMJ - Evergreen - HEC - In-Feed',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'status',
          value: 'ACTIVE',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'free_text_reporting',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'free_text_launch_doc_url',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'lifetime_spend',
          value: '457168.15',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'pacing_budget_lifetime',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'pacing_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'budget_progress_lifetime',
          value: null,
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'free_text_pacing',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'pacing_budget_lifetime_start_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'pacing_budget_lifetime_end_date',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'account',
          value: 'Accenture - GTM / Mazda FY155-FY157',
          columnStatusCode: null,
          columnStatusDescription: null,
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'publisher_budget_media',
          value: '62971737',
          columnStatusCode: 200,
          columnStatusDescription: ' Success. ',
        },
        {
          platform: 1,
          campaignId: 2,
          campaignKey: '23853866375680209',
          campaignDashColumnKey: 'pacing_budget_current_segment',
          value: null,
          columnStatusCode: null,
          columnStatusDescription: null,
        },
      ],
    },
  ],
};

export const cellData = {
  openModal: true,
  title: 'Test Title',
  formHeight: '450px',
  onSaveText: 'Ok',
  onCloseText: 'Cancel',
  data: {
    cell: {
      id: '0_free_text_reporting',
      row: {
        id: '0',
        index: 0,
        original: {
          campaign_key: '6094429360798',
          campaignId: 1,
          campaign_name: 'C1176 Test Campaign do not remove',
          status: 'ACTIVE',
          free_text_reporting: 'test',
          free_text_launch_doc_url: null,
          lifetime_spend: '0',
          pacing_budget_lifetime: null,
          pacing_lifetime: null,
          budget_progress_lifetime: null,
          free_text_pacing: null,
          pacing_budget_lifetime_start_date: null,
          pacing_budget_lifetime_end_date: null,
          account: 'Accenture Automation Tests',
          publisher_budget_media: '1000000',
          pacing_budget_current_segment: null,
        },
      },
      column: {
        id: 'free_text_reporting',
        depth: 0,
        columnDef: {
          header: 'free_text_reporting',
          filterFn: 'fuzzy',
          sortingFn: 'auto',
          size: 150,
          minSize: 20,
          maxSize: 9007199254740991,
          minWidth: 70,
          width: 175,
          maxWidth: 1000,
          canGroupBy: true,
          accessorKey: 'free_text_reporting',
          tooltipText: 'Free Text: Reporting',
          columnGroup: 'inputs',
          editor: 'notesEditor',
        },
      },
    },
    campaignId: 1,
    campaignKey: '6094429360798',
  },
};

export const cellDataForDemoValues = {
  openModal: true,
  title: 'Test Title',
  formHeight: '450px',
  onSaveText: 'Ok',
  onCloseText: 'Cancel',
  data: {
    cell: {
      id: '0_free_text_reporting',
      row: {
        id: '0',
        index: 0,
        original: {
          campaign_key: '6094429360798',
          campaignId: 1,
          campaign_name: 'C1176 Test Campaign do not remove',
          status: 'ACTIVE',
          free_text_reporting: 'test',
          free_text_launch_doc_url: null,
          lifetime_spend: '0',
          pacing_budget_lifetime: null,
          pacing_lifetime: null,
          budget_progress_lifetime: null,
          free_text_pacing: null,
          pacing_budget_lifetime_start_date: null,
          pacing_budget_lifetime_end_date: null,
          account: 'Accenture Automation Tests',
          publisher_budget_media: '1000000',
          pacing_budget_current_segment: null,
          maskedValues:{ 
            budgetRecTooltipMaskedValue: "Tooltip"
          }
        },
      },
      column: {
        id: 'budget_recommendation',
        depth: 0,
        columnDef: {
          header: 'free_text_reporting',
          filterFn: 'fuzzy',
          sortingFn: 'auto',
          size: 150,
          minSize: 20,
          maxSize: 9007199254740991,
          minWidth: 70,
          width: 175,
          maxWidth: 1000,
          canGroupBy: true,
          accessorKey: 'free_text_reporting',
          tooltipText: 'Free Text: Reporting',
          columnGroup: 'inputs',
          editor: 'notesEditor',
        },
      },
    },
    campaignId: 1,
    campaignKey: '6094429360798',
  },
};

export const budgetSegmentData = {
  selectedCampaign: 8,
  data: [
    {
      id: 1,
      campaignSelectedId: 8,
      platformId: 1,
      campaignDashUserId: null,
      campaignDashViewId: null,
      pacingBudget: 100,
      startDate: '2023-07-12',
      endDate: '2023-07-24',
      notes: 'test',
      spend: 10,
    },
  ],
  rowData: [
    `${numberToCurrencyFormat(10)}`,
    `${numberToCurrencyFormat(100)}`,
    `${moment('2023-07-12').format('MMM-DD-YYYY')}`,
    `${moment('2023-07-24').format('MMM-DD-YYYY')}`,
    'test',
    '',
  ],
  modalOpen: true,
};

export const pacingBudgetData = [
  {
    id: 1,
    campaignSelectedId: 8,
    platformId: 1,
    campaignDashUserId: null,
    campaignDashViewId: null,
    pacingBudget: 100,
    startDate: '2023-07-12',
    endDate: '2023-07-24',
    notes: 'test',
    spend: 200,
  },
  {
    id: 8,
    campaignSelectedId: 8,
    platformId: 1,
    campaignDashUserId: null,
    campaignDashViewId: null,
    pacingBudget: 500,
    startDate: '2023-07-25',
    endDate: '2023-07-25',
    notes: '',
    spend: 30.2,
  },
];

export const getPlatformBudgetRes = {
  statusCode: 200,
  statusDescription: ' Success. ',
  json: [
    {
      campaignId: 382,
      campaignKey: 38225266,
      campaignName: 'Competitors - Branded',
      campaignBudgetId: 10439597426,
      budgetValue: 10,
      budgetType: 'Daily',
      platformId: 0,
      userId: 0,
      campaignDashUserId: null,
      campaignDashViewId: null,
      campaignSelectedId: 0,
    },
  ],
  rowData: [
    'Competitors - Branded',
    '38225266',
    'Daily',
    `${numberToCurrencyFormat(10)}`
  ],
  budgetEditor: {
    cellField: 'platform_campaign_budget',
    platformId: 4,
    userId: 84,
    campaignDashUserId: 84,
    campaignDashViewId: 168,
    campaignSelectedId: 382,
  },
  modalOpen: true,
};

export const savedViewsListData = {
  id: 2,
  name: 'Default View',
  userId: 10,
  isDefault: true,
  isSelected: true,
  label: "Default View",
  freezeColumns: 1,
  selected: true,
  columns: ['campaign_name', 'status', 'free_text_reporting', 'free_text_launch_doc_url', 'lifetime_spend', 'pacing_budget_lifetime', 'pacing_lifetime', 'budget_progress_lifetime'],
  columnList: [
    { id: 1, viewId: 1, columnKey: 'campaign_name', userId: 10, displayOrder: 1, isFreeze: true },
    { id: 2, viewId: 1, columnKey: 'status', userId: 10, displayOrder: 2, isFreeze: true }
  ]
}

export const mockConfigureStatusActiveData = {
  original: {
    platform: 1,
    campaign_key: '1',
    campaignId: 1,
    campaign_name: 'Test',
    publisher: 'Facebook',
    account: null,
    status: 'Active',
    platform_native_status: 'Active',
    free_text_notes_1: null,
  },
}

export const mockConfigureStatusPausedData = {
  original: {
    platform: 1,
    campaign_key: '1',
    campaignId: 1,
    campaign_name: 'Test',
    publisher: 'Facebook',
    account: null,
    status: 'Paused',
    platform_native_status: 'Paused',
    free_text_notes_1: null,
  },
}
