const TooltipTexts = {
  CAMPAIGN_NAME: 'Campaign Name',
  ACCOUNT: 'Account',
  CURRENT_BUDG_SEGM_SPEND: 'Current Budget Segment Spend',
  YESTERDAY_SPEND: 'Yesterday Spend',
  TODAY_SPEND: 'Today Spend',
  CAMPAIGN_ID: 'Campaign ID',
  PUBLISHER: 'Platform',
  PUBLISHER_BUDGET: 'Publisher Budget (Media)',
  STATS_LAST_UPDATED: 'Stats Last Updated',
  DATA_PROVIDER_AND_FEE: 'Data Provider and Fee',
  PAC_BUDG_CURRT_SEGM: 'Pacing Budget',
  PAC_BUDG_END_DATE_CURRT_SEGM: 'Pacing Budget End Date',
  PAC_BUDG_START_DATE_CURRT_SEGM: 'Pacing Budget Start Date',
  BUDGET_GROUP: 'Budget Group',
  FREE_TEXT_LAUNCH_DOC_URL: 'Free Text: Launch Doc URL',
  FREE_TEXT_NOTES_1: 'Free Text: Notes 1',
  FREE_TEXT_NOTES_2: 'Free Text: Notes 2',
  FREE_TEXT_NOTES_3: 'Free Text: Notes 3',
  FREE_TEXT_PACING: 'Free Text: Pacing',
  FREE_TEXT_REPORTING: 'Free Text: Reporting',
  DAYS_REMAINING: 'Days Remaining - The days remaining in the current segment or in flight.  -- Pacing Budget End Date - Current Date. -- Format - Absolute values',
  YESTERDAY_SPEND_TARGET_REACHED: "Yesterday Spend Target Reached - Yesterday's spend target reached % of spend reached yesterday based on the current target. -- Yesterday's Spend / Target Daily Spend   -- Format - %",
  AVG_GOAL_BILLABLE_CURRENT_SEGMENT: 'Average Daily Goal Spend - Campaign average goal target spend (cost) divided by the amount of days in the campaign current budget segment.  -- Campaign Current Budget / (Current Budget Segment End Date –  Current Pacing Budget Start Date). -- Format - Currency',
  AVG_DAILY_BILLABLE_CURRENT_SEGMENT: 'Average Daily Spend - Campaign average daily spend (cost) based on the amount of days that campaign current budget segment.  -- Spend in the Current Segment / Num of Days elapsed in campaign in the Current Segment. -- Format - Currency',
  BUDGET_PROGRESS_CURRENT_SEGMENT: 'Budget Progress - Percentage budget spent on the Current Segment.  -- Current segment spend / Current Segment Budget -- Format - %',
  FLIGHT_PROGRESS_CURRENT_SEGMENT: 'Flight Progress - Percentage of days elapsed in the Current Segment. -- Number of Days Elapsed in the Current Segment / Total Number of Days in Current Segment.  -- Format - %',
  PACING_CURRENT_SEGMENT: 'Pacing - Percentage below or above target daily spend. Ideal value for this field is as close to 0% as possible.  -- (Average Daily Spend in the Current Segment - Average Goal Spend) / Average Goal Spend in the Current Segment -- Format - %',
  TARGET_DAILY_BILLABLE: "Target Daily Spend - Target daily based on the campaign's budget left and flight spend. Daily spend required to satisfy current budget segment remaining budget. -- (Pacing Budget – L Spend thru Y) / number of days remaining including today. -- Format - Currency",
  STATUS: 'Status',
  CONFIGURED_STATUS: 'Configured Status',
  KPI_1: 'KPI 1',
  KPI_2: 'KPI 2',
  KPI_3: 'KPI 3',
  IS_CHECK_IN_AM: 'Check-In AM',
  IS_CHECK_IN_PM: 'Check-In PM',
  KPI1_UNITS_DELIVERED_CURRENT_SEGMENT: 'KPI 1 Units Delivered',
  KPI2_UNITS_DELIVERED_CURRENT_SEGMENT: 'KPI 2 Units Delivered',
  KPI3_UNITS_DELIVERED_CURRENT_SEGMENT: 'KPI 3 Units Delivered',
  KPI1_AVG_UNIT_COST_CURRENT_SEGMENT: 'KPI 1 Average Unit Cost',
  KPI2_AVG_UNIT_COST_CURRENT_SEGMENT: 'KPI 2 Average Unit Cost',
  KPI3_AVG_UNIT_COST_CURRENT_SEGMENT: 'KPI 3 Average Unit Cost',
  BUDGET_RECOMMENDATION: 'The In-Flight Budget Recommendation is a machine learning algorithm that takes various campaign input and generates a recommended daily budget value that the user can update the campaign daily budget for optimization.',
  PLATFORM_CAMPAIGN_BUDGET: 'Platform Budget'
}

export default TooltipTexts;