const HeaderNames = {
  ACCOUNT: 'account',
  CAMPAIGN_NAME: 'campaign_name',
  CURRENT_BUDG_SEGM_SPEND: 'current_segment_spend',
  YESTERDAY_SPEND: 'yesterday_spend',
  TODAY_SPEND: 'today_spend',
  CAMPAIGN_ID: 'campaign_key',
  PUBLISHER: 'publisher',
  PUBLISHER_BUDGET: 'publisher_budget_media',
  STATS_LAST_UPDATED: 'stats_last_updated',
  DATA_PROVIDER_AND_FEE: 'data_provider_and_fee',
  PAC_BUDG_CURRT_SEGM: 'pacing_budget_current_segment',
  PAC_BUDG_END_DATE_CURRT_SEGM: 'pacing_budget_current_segment_end_date',
  PAC_BUDG_START_DATE_CURRT_SEGM: 'pacing_budget_current_segment_start_date',
  BUDGET_GROUP: 'budget_group',
  FREE_TEXT_LAUNCH_DOC_URL: 'free_text_launch_doc_url',
  FREE_TEXT_NOTES_1: 'free_text_notes_1',
  FREE_TEXT_NOTES_2: 'free_text_notes_2',
  FREE_TEXT_NOTES_3: 'free_text_notes_3',
  FREE_TEXT_PACING: 'free_text_pacing',
  FREE_TEXT_REPORTING: 'free_text_reporting',
  DAYS_REMAINING: 'days_remaining',
  YESTERDAY_SPEND_TARGET_REACHED: 'yesterday_spend_target_reached',
  AVG_GOAL_BILLABLE_CURRENT_SEGMENT: 'average_daily_goal_spend_current_segment',
  AVG_DAILY_BILLABLE_CURRENT_SEGMENT: 'average_daily_spend_current_segment',
  BUDGET_PROGRESS_CURRENT_SEGMENT: 'budget_progress_current_segment',
  FLIGHT_PROGRESS_CURRENT_SEGMENT: 'flight_progress_current_segment',
  PACING_CURRENT_SEGMENT: 'pacing_current_segment',
  TARGET_DAILY_BILLABLE: 'target_daily_spend_current_segment',
  STATUS: 'status',
  CONFIGURED_STATUS: 'platform_native_status',
  KPI_1: 'kpi1',
  KPI_2: 'kpi2',
  KPI_3: 'kpi3',
  IS_CHECK_IN_AM: 'is_check_in_am',
  IS_CHECK_IN_PM: 'is_check_in_pm',
  KPI1_UNITS_DELIVERED_CURRENT_SEGMENT: 'kpi1_units_delivered_current_segment',
  KPI2_UNITS_DELIVERED_CURRENT_SEGMENT: 'kpi2_units_delivered_current_segment',
  KPI3_UNITS_DELIVERED_CURRENT_SEGMENT: 'kpi3_units_delivered_current_segment',
  KPI1_AVG_UNIT_COST_CURRENT_SEGMENT: 'kpi1_average_unit_cost_current_segment',
  KPI2_AVG_UNIT_COST_CURRENT_SEGMENT: 'kpi2_average_unit_cost_current_segment',
  KPI3_AVG_UNIT_COST_CURRENT_SEGMENT: 'kpi3_average_unit_cost_current_segment',
  BUDGET_RECOMMENDATION: 'budget_recommendation',
  PLATFORM_CAMPAIGN_BUDGET: 'platform_campaign_budget',
};

export default HeaderNames;
