const HeaderNames = {
   NAME: {'campaign': 'campaign_name', 'adSet': 'ad_set_name', 'ads': 'ad_name'},
   ID: { 'campaign': 'campaign_key', 'adSet': 'ad_set_id', 'ads': 'ad_id'},
   STATUS: 'status',
   STATUS_DETAILS: 'status_details',
   SPEND_CAP_USABLE: 'spend_cap_usable',
   M_SPEND_CAP: 'm_spend_cap',
   CONFIGURED_STATUS: { 'campaign': 'Campaign Configured Status', 'adSet': 'Ad Set ID', 'ads': 'Ad ID'},
   TARGETING_EXPANSION: 'targeting_expansion',
   DATE_CREATED: 'date_created',
   DATE_UPDATED: 'date_updated',
   BUYING_TYPE: 'buying_type',
   CAMPAIGN_OBJECTIVE: 'campaign_objective',
   START_DATE: 'start_date',
   SPECIAL_AD_CATEGORIES: 'special_ad_categories',
   SPEND: 'spend',
   IMPRESSIONS: 'impressions',
   BILLING_EVENT: 'billing_event',
   AGE_RANGE: 'age_range',
   CONNECTIONS: 'connections',
   CUSTOM_AUDIENCES: 'custom_audiences',
   DELIVERY_TYPE: 'delivery_type',
   DESTINATION_TYPE: 'destination_type',
   END_DATE: 'end_date',
   EXCLUDED_CONNECTIONS: 'excluded_connections',
   EXCLUDED_CUSTOM_AUDIENCES: 'excluded_custom_audiences',
   EXCLUDED_LOCATIONS: 'excluded_locations',
   FREQUENCY_CAP: 'frequency_cap',
   GENDERS: 'genders',
   LOCATION_TYPE: 'location_types',
   PLACEMENTS: 'placements',
   SAVED_AUDIENCE: 'saved_audience',
   TARGETING_SPEC: 'targeting_spec',
   USER_DEVICE: 'user_device',
   USER_OS: 'user_os',
   WIFI: 'wifi_only?',
   ADS_LAST_UPDATED_S4M: 'ads_last_updated_in_s4m?',
   LAST_UPDATED_S4M: 'last_updated_in_s4m?',
   BID_AMOUNT: 'bid_amount',
   BODY: 'body',
   CALL_TO_ACTION: 'call_to_action',
   CONVERSION_SPECS: 'conversion_specs',
   EVENT: 'event',
   IS_INLINE: 'is_inline?',
   OFFER_ID_CREATIVE: 'offer_id_creative',
   OFFLINE_TRACKING_EVENTS_SETS: 'offline_tracking_event_sets',
   POST_ID: 'post_id',
   RELATED_PAGE: 'related_page',
   PREVIEW_LINK: 'preview_link',
   PRODUCT_SET_ID: 'product_set_id_creative',
   TRACKING_SPECS: 'tracking_specs',
   TRACKING_PIXEL: 'tracking_pixel',
   URL_PARAMETERS: 'url_parameters',
   VIEW_TAGS: 'view_tags',
   VIDEO: 'video',
   IMAGE: 'image',
}

export default HeaderNames;