import _ from 'underscore';
import * as CellFormatters from './cellFormatters';


const platform = 'googleads';

export const standardKpiMetricsFields = [
  {value: "absolute_top_impression_percentage", label: "'Impr. (Abs. Top) % (Google Ads)'"},
  {value: "active_view_cpm", label: "'Active View avg. CPM (Google Ads)'"},
  {value: "active_view_ctr", label: "'Active View viewable CTR (Google Ads)'"},
  {value: "active_view_impressions", label: "'Active View viewable impressions (Google Ads)'"},
  {value: "active_view_measurability", label: "'Active View measurable impr. / impr. (Google Ads)'"},
  {value: "active_view_measurable_cost_micros", label: "'Active View measurable cost (Google Ads)'"},
  {value: "active_view_measurable_impressions", label: "'Active View measurable impr. (Google Ads)'"},
  {value: "active_view_viewability", label: "'Active View viewable impr. / measurable impr. (Google Ads)'"},
  {value: "all_conversions", label: "'All conv. (Google Ads)'"},
  {value: "average_time_on_site", label: "'Avg. session duration (seconds) (Google Ads)'"},
  {value: "bounce_rate", label: "'Bounce rate (Google Ads)'"},
  {value: "clicks", label: "'Clicks (Google Ads)'"},
  {value: "content_budget_lost_impression_share", label: "'Content Lost IS (budget) (Google Ads)'"},
  {value: "content_impression_share", label: "'Content Impr. share (Google Ads)'"},
  {value: "content_rank_lost_impression_share", label: "'Content Lost IS (rank) (Google Ads)'"},
  {value: "conversions", label: "'Conversions (Google Ads)'"},
  {value: "conversions_value", label: "'Total conv. value (Google Ads)'"},
  {value: "cost_micros", label: "'Cost (Google Ads)'"},
  {value: "cross_device_conversions", label: "'Cross-device conv. (Google Ads)'"},
  {value: "current_model_attributed_conversions", label: "'Conversions (current model) (Google Ads)'"},
  {value: "current_model_attributed_conversions_value", label: "'Conv. value (current model) (Google Ads)'"},
  {value: "engagement_rate", label: "'Engagement rate (Google Ads)'"},
  {value: "engagements", label: "'Engagements (Google Ads)'"},
  {value: "gmail_forwards", label: "'Gmail forwards (Google Ads)'"},
  {value: "gmail_saves", label: "'Gmail saves (Google Ads)'"},
  {value: "gmail_secondary_clicks", label: "'Gmail clicks to website (Google Ads)'"},
  {value: "impressions", label: "'Impressions (Google Ads)'"},
  {value: "interaction_rate", label: "'Interaction Rate (Google Ads)'"},
  {value: "interactions", label: "'Interactions (Google Ads)'"},
  {value: "invalid_click_rate", label: "'Invalid click rate (Google Ads)'"},
  {value: "invalid_clicks", label: "'Invalid clicks (Google Ads)'"},
  {value: "percent_new_visitors", label: "'Percent new sessions (Google Ads)"},
  {value: "search_absolute_top_impression_share", label: "'Search abs. top IS (Google Ads)'"},
  {value: "search_budget_lost_absolute_top_impression_share", label: "'Search lost abs. top IS (budget) (Google Ads)'"},
  {value: "search_budget_lost_impression_share", label: "'Search Lost IS (budget) (Google Ads)'"},
  {value: "search_budget_lost_top_impression_share", label: "'Search lost top IS (budget) (Google Ads)'"},
  {value: "search_click_share", label: "'Click share (Google Ads)'"},
  {value: "search_exact_match_impression_share", label: "'Search Exact match IS (Google Ads)'"},
  {value: "search_impression_share", label: "'Search Impr. share (Google Ads)'"},
  {value: "search_rank_lost_absolute_top_impression_share", label: "'Search lost abs. top IS (rank) (Google Ads)'"},
  {value: "search_rank_lost_impression_share", label: "'Search Lost IS (rank) (Google Ads)'"},
  {value: "search_rank_lost_top_impression_share", label: "'Search lost top IS (rank) (Google Ads)'"},
  {value: "search_top_impression_share", label: "'Search top IS (Google Ads)'"},
  {value: "top_impression_percentage", label: "'Impr. (Top) % (Google Ads)'"},
  {value: "video_quartile_p100_rate", label: "'Video played to 100% (Google Ads)'"},
  {value: "video_quartile_p25_rate", label: "'Video played to 25% (Google Ads)'"},
  {value: "video_quartile_p50_rate", label: "'Video played to 50% (Google Ads)'"},
  {value: "video_quartile_p75_rate", label: "'Video played to 75% (Google Ads)'"},
  {value: "video_view_rate", label: "'View rate (Google Ads)'"},
  {value: "video_views", label: "'Views (Google Ads)'"},
  {value: "view_through_conversions", label: "'View-through conv. (Google Ads)'"},
  {value: "all_conversions", label: "'All conv. (Google Ads)'"},
  {value: "value_per_all_conversions", label: "'Value / all conv. (Google Ads)'"}
]
