export const standardKpiMetricsFields = [
  {value: "METRIC_IMPRESSIONS", label: "'Impressions (Google DV360)'"},
  {value: "METRIC_CLICKS", label: "'Clicks (Google DV360)'"},
  {value: "METRIC_BILLABLE_IMPRESSIONS", label: "'Billable Impressions (Google DV360)'"},
  {value: "METRIC_TOTAL_CONVERSIONS", label: "'Total Conversions (Google DV360)'"},
  {value: "METRIC_LAST_CLICKS", label: "'Post-Click Conversions (Google DV360)'"},
  {value: "METRIC_LAST_IMPRESSIONS", label: "'Post-View Conversions (Google DV360)'"},
  {value: "METRIC_REVENUE_ADVERTISER", label: "'Revenue (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_MEDIA_COST_ADVERTISER", label: "'Media Cost (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_TOTAL_MEDIA_COST_ADVERTISER", label: "'Total Media Cost (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_FIRST_QUARTILE_COMPLETES", label: "'First-Quartile Views (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_MIDPOINTS", label: "'Midpoint Views (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_THIRD_QUARTILE_COMPLETES", label: "'Third-Quartile Views (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_COMPLETIONS", label: "'Complete Views (Video) (Google DV360)'"},
  {value: "METRIC_TRUEVIEW_VIEWS", label: "'TrueView: Views (Google DV360)'"},
  {value: "METRIC_PROFIT_ADVERTISER", label: "'Profit (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_FULL_SCREENS", label: "'Fullscreens (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_PAUSES", label: "'Pauses (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_SCROLLS", label: "'Scrolls (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_PLAYS", label: "'Starts (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_MUTES", label: "'Audio Mutes (Video) (Google DV360)'"},
  {value: "METRIC_RICH_MEDIA_VIDEO_SKIPS", label: "'Skips (Video) (Google DV360)'"},
  {value: "METRIC_VIDEO_COMPANION_CLICKS", label: "'Companion Clicks (Video) (Google DV360)'"},
  {value: "METRIC_VIDEO_COMPANION_IMPRESSIONS", label: "'Companion Views (Video) (Google DV360)'"},
  {value: "METRIC_MEDIA_FEE5_ADVERTISER", label: "'Media Fee 5 (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_MEDIA_FEE4_ADVERTISER", label: "'Media Fee 4 (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_MEDIA_FEE3_ADVERTISER", label: "'Media Fee 3 (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_MEDIA_FEE2_ADVERTISER", label: "'Media Fee 2 (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_MEDIA_FEE1_ADVERTISER", label: "'Media Fee 1 (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_DATA_COST_ADVERTISER", label: "'Data Fees  (Advertiser Currency) (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_AVERAGE_VIEWABLE_TIME", label: "'Active View: Average Viewable Time (seconds) (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_ELIGIBLE_IMPRESSIONS", label: "'Active View: Eligible Impressions (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_DISTRIBUTION_UNMEASURABLE", label: "'Active View: Impression Distribution (Not Measurable) (Google DV360)"},
  {value: "METRIC_ACTIVE_VIEW_DISTRIBUTION_UNVIEWABLE", label: "'Active View: Impression Distribution (Not Viewable) (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_DISTRIBUTION_VIEWABLE", label: "'Active View: Impression Distribution (Viewable) (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_AUDIBLE_VISIBLE_ON_COMPLETE_IMPRESSIONS", label: "'Active View: Impressions Audible and Visible at Completion (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_VIEWABLE_FOR_TIME_THRESHOLD", label: "'Active View: Impressions Visible 10 Seconds (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_MEASURABLE_IMPRESSIONS", label: "'Active View: Measurable Impressions (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_UNMEASURABLE_IMPRESSIONS", label: "'Active View: Not Measurable Impressions (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_UNVIEWABLE_IMPRESSIONS", label: "'Active View: Not Viewable Impressions (Google DV360)'"},
  {value: "METRIC_ACTIVE_VIEW_VIEWABLE_IMPRESSIONS", label: "'Active View: Viewable Impressions (Google DV360)'"}
]
