import * as _ from 'underscore';
import HeaderNames from './linkedinHeaderNames';

export const defaultColumns = [
  [HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.CAMPAIGN_GROUP_ID, HeaderNames.STATUS, HeaderNames.IMPRESSIONS, HeaderNames.SPEND, HeaderNames.CLICKS],
  [HeaderNames.CAMPAIGN_NAME, HeaderNames.CAMPAIGN_ID, HeaderNames.STATUS, HeaderNames.IMPRESSIONS, HeaderNames.SPEND],
  [HeaderNames.CREATIVE_ID, HeaderNames.STATUS, HeaderNames.IMPRESSIONS, HeaderNames.SPEND]
];

export const preDefinedViews = [
  {label: 'Performance', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.BID, HeaderNames.AVERAGE_CPM, HeaderNames.AVERAGE_CPC, HeaderNames.CONVERSIONS, HeaderNames.COST_PER_CONVERSION, HeaderNames.LEADS, HeaderNames.COST_PER_LEAD,HeaderNames.EVENT_REGISTRATIONS],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.BID, HeaderNames.AVERAGE_CPM, HeaderNames.AVERAGE_CPC, HeaderNames.CONVERSIONS, HeaderNames.COST_PER_CONVERSION, HeaderNames.LEADS, HeaderNames.COST_PER_LEAD, HeaderNames.EVENT_REGISTRATIONS],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.BID, HeaderNames.AVERAGE_CPM, HeaderNames.AVERAGE_CPC, HeaderNames.CONVERSIONS, HeaderNames.COST_PER_CONVERSION, HeaderNames.LEADS, HeaderNames.COST_PER_LEAD, HeaderNames.EVENT_REGISTRATIONS]]},
  {label: 'Delivery', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.REACH, HeaderNames.AVERAGE_FREQUENCY, HeaderNames.AVERAGE_CPM, HeaderNames.COST_PER_THOUSAND_MEMBERS],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.REACH, HeaderNames.AVERAGE_FREQUENCY, HeaderNames.AVERAGE_CPM, HeaderNames.COST_PER_THOUSAND_MEMBERS],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.REACH, HeaderNames.AVERAGE_FREQUENCY, HeaderNames.AVERAGE_CPM, HeaderNames.COST_PER_THOUSAND_MEMBERS]]},
  {label: 'Engagement', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.REACTIONS, HeaderNames.COMMENTS, HeaderNames.SHARES, HeaderNames.FOLLOWS, HeaderNames.OTHER, HeaderNames.TOTAL_SOCIAL_ACTIONS, HeaderNames.LANDING_PAGE_CLICKS, HeaderNames.LINKEDIN_PAGE_CLICKS, HeaderNames.TOTAL_ENGAGEMENTS, HeaderNames.ENGAGEMENT_RATE],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.REACTIONS, HeaderNames.COMMENTS, HeaderNames.SHARES, HeaderNames.FOLLOWS, HeaderNames.OTHER, HeaderNames.TOTAL_SOCIAL_ACTIONS, HeaderNames.LANDING_PAGE_CLICKS, HeaderNames.LINKEDIN_PAGE_CLICKS, HeaderNames.TOTAL_ENGAGEMENTS, HeaderNames.ENGAGEMENT_RATE],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.REACTIONS, HeaderNames.COMMENTS, HeaderNames.SHARES, HeaderNames.FOLLOWS, HeaderNames.OTHER, HeaderNames.TOTAL_SOCIAL_ACTIONS, HeaderNames.LANDING_PAGE_CLICKS, HeaderNames.LINKEDIN_PAGE_CLICKS, HeaderNames.TOTAL_ENGAGEMENTS, HeaderNames.ENGAGEMENT_RATE]]},
  {label: 'Conversion & Leads', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.CONVERSIONS, HeaderNames.CLICK_CONVERSIONS, HeaderNames.VIEW_CONVERSIONS, HeaderNames.CONVERSIONS_RATE, HeaderNames.COST_PER_CONVERSION, HeaderNames.TOTAL_CONVERSIONS_VALUE, HeaderNames.RETURN_ON_AD_SPEND, HeaderNames.LEADS, HeaderNames.LEAD_FORM_OPENS, HeaderNames.LEAD_FORM_COMPLETION_RATE, HeaderNames.COST_PER_LEAD, HeaderNames.EVENT_REGISTRATIONS, HeaderNames.CLICK_EVENT_REGISTRATIONS, HeaderNames.VIEW_EVENT_REGISTRATIONS],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.CONVERSIONS, HeaderNames.CLICK_CONVERSIONS, HeaderNames.VIEW_CONVERSIONS, HeaderNames.CONVERSIONS_RATE, HeaderNames.COST_PER_CONVERSION, HeaderNames.TOTAL_CONVERSIONS_VALUE, HeaderNames.RETURN_ON_AD_SPEND, HeaderNames.LEADS, HeaderNames.LEAD_FORM_OPENS, HeaderNames.LEAD_FORM_COMPLETION_RATE, HeaderNames.COST_PER_LEAD, HeaderNames.EVENT_REGISTRATIONS, HeaderNames.CLICK_EVENT_REGISTRATIONS, HeaderNames.VIEW_EVENT_REGISTRATIONS],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.CONVERSIONS, HeaderNames.CLICK_CONVERSIONS, HeaderNames.VIEW_CONVERSIONS, HeaderNames.CONVERSIONS_RATE, HeaderNames.COST_PER_CONVERSION, HeaderNames.TOTAL_CONVERSIONS_VALUE, HeaderNames.RETURN_ON_AD_SPEND, HeaderNames.LEADS, HeaderNames.LEAD_FORM_OPENS, HeaderNames.LEAD_FORM_COMPLETION_RATE, HeaderNames.COST_PER_LEAD, HeaderNames.EVENT_REGISTRATIONS, HeaderNames.CLICK_EVENT_REGISTRATIONS, HeaderNames.VIEW_EVENT_REGISTRATIONS]]},
  {label: 'Sponsored Messaging', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.SENDS, HeaderNames.OPENS, HeaderNames.SPONSORED_MESSAGING_CLICKS, HeaderNames.BANNER_CLICKS, HeaderNames.BUTTON_CLICKS, HeaderNames.LINK_CLICKS, HeaderNames.OPEN_RATE, HeaderNames.CLICKS_OPEN_RATE, HeaderNames.COST_PER_SEND, HeaderNames.COST_PER_OPEN, HeaderNames.AVERAGE_CPC],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.SENDS, HeaderNames.OPENS, HeaderNames.SPONSORED_MESSAGING_CLICKS, HeaderNames.BANNER_CLICKS, HeaderNames.BUTTON_CLICKS, HeaderNames.LINK_CLICKS, HeaderNames.OPEN_RATE, HeaderNames.CLICKS_OPEN_RATE, HeaderNames.COST_PER_SEND, HeaderNames.COST_PER_OPEN, HeaderNames.AVERAGE_CPC],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.SENDS, HeaderNames.OPENS, HeaderNames.SPONSORED_MESSAGING_CLICKS, HeaderNames.BANNER_CLICKS, HeaderNames.BUTTON_CLICKS, HeaderNames.LINK_CLICKS, HeaderNames.OPEN_RATE, HeaderNames.CLICKS_OPEN_RATE, HeaderNames.COST_PER_SEND, HeaderNames.COST_PER_OPEN, HeaderNames.AVERAGE_CPC]]},
  {label: 'Video', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.VIEWS, HeaderNames.VIEW_RATE, HeaderNames.ECVP, HeaderNames.VIEW_QUARTILE, HeaderNames.VIEW_MIDPOINT, HeaderNames.VIEW_THIRD_QUARTILE, HeaderNames.COMPLETIONS, HeaderNames.COMPLETION_RATE, HeaderNames.FULL_SCREEN_PLAY],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.VIEWS, HeaderNames.VIEW_RATE, HeaderNames.ECVP, HeaderNames.VIEW_QUARTILE, HeaderNames.VIEW_MIDPOINT, HeaderNames.VIEW_THIRD_QUARTILE, HeaderNames.COMPLETIONS, HeaderNames.COMPLETION_RATE, HeaderNames.FULL_SCREEN_PLAY],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.AVERAGE_CTR, HeaderNames.VIEWS, HeaderNames.VIEW_RATE, HeaderNames.ECVP, HeaderNames.VIEW_QUARTILE, HeaderNames.VIEW_MIDPOINT, HeaderNames.VIEW_THIRD_QUARTILE, HeaderNames.COMPLETIONS, HeaderNames.COMPLETION_RATE, HeaderNames.FULL_SCREEN_PLAY]]},
  {label: 'Budget & Bid', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.TOTAL_BUDGET, HeaderNames.BID, HeaderNames.START_DATE, HeaderNames.END_DATE],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.TOTAL_BUDGET, HeaderNames.AVG_DAILY_SPEND, HeaderNames.DAILY_BUDGET, HeaderNames.BID, HeaderNames.START_DATE, HeaderNames.END_DATE],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND]]},
  {label: 'Talent Leads', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.TALENT_LEADS, HeaderNames.TALENT_LEAD_RATE, HeaderNames.COST_PER_TALENT_LEAD],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.TALENT_LEADS, HeaderNames.TALENT_LEAD_RATE, HeaderNames.COST_PER_TALENT_LEAD],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.TALENT_LEADS, HeaderNames.TALENT_LEAD_RATE, HeaderNames.COST_PER_TALENT_LEAD]]},
  {label: 'Job Applicants', selected: false, isDefault: true,
   columns: [[HeaderNames.CAMPAIGN_GROUP_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.JOB_APPLY_CLICKS, HeaderNames.JOB_APPLICATIONS, HeaderNames.JOB_APPLICATION_RATE, HeaderNames.COST_PER_JOB_APPLICATION_LEAD],
             [HeaderNames.CAMPAIGN_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.JOB_APPLY_CLICKS, HeaderNames.JOB_APPLICATIONS, HeaderNames.JOB_APPLICATION_RATE, HeaderNames.COST_PER_JOB_APPLICATION_LEAD],
             [HeaderNames.AD_NAME, HeaderNames.STATUS, HeaderNames.SPEND, HeaderNames.IMPRESSIONS, HeaderNames.CLICKS, HeaderNames.JOB_APPLY_CLICKS, HeaderNames.JOB_APPLICATIONS, HeaderNames.JOB_APPLICATION_RATE, HeaderNames.COST_PER_JOB_APPLICATION_LEAD]]},
];

export const standardKpiMetricsFields = [
  {value: "actionClicks", label: "'Action Clicks'"},
  {value: "adUnitClicks", label: "'Ad Unit Clicks'"},
  {value: "cardClicks", label: "'Card Clicks'"},
  {value: "cardImpressions", label: "'Card Impressions'"},
  {value: "clicks", label: "'Clicks'"},
  {value: "commentLikes", label: "'Comment Likes'"},
  {value: "comments", label: "'Comments'"},
  {value: "companyPageClicks", label: "'Company Page Clicks'"},
  {value: "conversionValueInLocalCurrency", label: "'Conversion Value'"},
  {value: "costInLocalCurrency", label: "'Spend'"},
  {value: "externalWebsiteConversions", label: "'External Website Conversions'"},
  {value: "externalWebsitePostClickConversions", label: "'External Website Post Click Conversions'"},
  {value: "externalWebsitePostViewConversions", label: "'External Website Post View Conversions'"},
  {value: "follows", label: "'Follows'"},
  {value: "fullScreenPlays", label: "'Fullscreen Plays'"},
  {value: "impressions", label: "'Impressions'"},
  {value: "landingPageClicks", label: "'Landing Page Clicks'"},
  {value: "leadGenerationMailContactInfoShares", label: "'Lead Generation Mail Contact Info Shares'"},
  {value: "leadGenerationMailInterestedClicks", label: "'Lead Generation Mail Interested Clicks'"},
  {value: "likes", label: "'Likes'"},
  {value: "oneClickLeadFormOpens", label: "'One Click Lead Form Opens'"},
  {value: "oneClickLeads", label: "'One Click Leads'"},
  {value: "opens", label: "'Opens'"},
  {value: "otherEngagements", label: "'Other Engagements'"},
  {value: "shares", label: "'Shares'"},
  {value: "textUrlClicks", label: "'Text Url Clicks'"},
  {value: "totalEngagements", label: "'Total Engagements'"},
  {value: "videoCompletions", label: "'Video Completions'"},
  {value: "videoFirstQuartileCompletions", label: "'Video First Quartile Completions'"},
  {value: "videoMidpointCompletions", label: "'Video Midpoint Completions'"},
  {value: "videoStarts", label: "'Video Starts'"},
  {value: "videoThirdQuartileCompletions", label: "'Video Third Quartile Completions"},
  {value: "videoViews", label: "'Video Views'"},
  {value: "viralCardClicks", label: "'Viral Card Clicks'"},
  {value: "viralCardImpressions", label: "'Viral Card Impressions'"},
  {value: "viralClicks", label: "'Viral Clicks'"},
  {value: "viralComments", label: "'Viral Comments'"},
  {value: "viralCompanyPageClicks", label: "'Viral Company Page Clicks'"},
  {value: "viralExternalWebsiteConversions", label: "'Viral External Website Conversions'"},
  {value: "viralExternalWebsitePostClickConversions", label: "'Viral External Website Post Click Conversions'"},
  {value: "viralExternalWebsitePostViewConversions", label: "'Viral External Website Post View Conversions'"},
  {value: "viralFollows", label: "'Viral Follows'"},
  {value: "viralFullScreenPlays", label: "'Viral Fullscreen Plays'"},
  {value: "viralImpressions", label: "'Viral Impressions'"},
  {value: "viralLandingPageClicks", label: "'Viral Landing Page Clicks'"},
  {value: "viralLikes", label: "'Viral Likes'"},
  {value: "viralOneClickLeadFormOpens", label: "'Viral One Click Lead Form Opens'"},
  {value: "viralOneClickLeads", label: "'Viral One Click Leads'"},
  {value: "viralOtherEngagements", label: "'Viral Other Engagements'"},
  {value: "viralShares", label: "'Viral Shares'"},
  {value: "viralTotalEngagements", label: "'Viral Total Engagements'"},
  {value: "viralVideoCompletions", label: "'Viral Video Completions'"},
  {value: "viralVideoFirstQuartileCompletions", label: "'Viral Video First Quartile Completions'"},
  {value: "viralVideoMidpointCompletions", label: "'Viral Video Midpoint Completions'"},
  {value: "viralVideoStarts", label: "'Viral Video Starts'"},
  {value: "viralVideoThirdQuartileCompletions", label: "'Viral Video Third Quartile Completions'"},
  {value: "viralVideoViews", label: "'Viral Video Views'"}
]
