const HeaderNames = {
  STATUS: 'Status',
  SPEND: 'Spend',
  OBJECTIVE: 'Objective',
  START_DATE: 'Start Date',
  END_DATE: 'End Date',
  AVG_DAILY_SPEND: 'Avg. Daily Spend',
  TOTAL_BUDGET: 'Total Budget',
  DAILY_BUDGET: 'Daily Budget',
  BID: 'Bid',
  IMPRESSIONS: 'Impressions',
  CLICKS: 'Clicks',
  AVERAGE_CPM: 'Average CPM',
  AVERAGE_CPC: 'Average CPC',
  REACH: 'Reach',
  AVERAGE_FREQUENCY: 'Average Frequency',
  COST_PER_THOUSAND_MEMBERS: 'Cost per 1,000 member accounts reached',
  AVERAGE_CTR: 'Average CTR',
  REACTIONS: 'Reactions',
  COMMENTS: 'Comments',
  SHARES: 'Shares',
  FOLLOWS: 'Follows',
  OTHER: 'Other',
  TOTAL_SOCIAL_ACTIONS: 'Total Social Actions',
  LANDING_PAGE_CLICKS: 'Clicks to Landing Page',
  LINKEDIN_PAGE_CLICKS: 'Clicks to LinkedIn Page',
  TOTAL_ENGAGEMENTS: 'Total Engagements',
  ENGAGEMENT_RATE: 'Engagement Rate',
  VIRAL_IMPRESSIONS: 'Viral Impressions',
  VIRAL_CLICKS: 'Viral Clicks',
  VIRAL_REACTIONS: 'Viral Reactions',
  VIRAL_COMMENTS: 'Viral Comments',
  VIRAL_SHARES: 'Viral Shares',
  VIRAL_FOLLOWS: 'Viral Follows',
  VIRAL_OTHER: 'Viral Other',
  VIRAL_CONVERSIONS: 'Viral Conversions',
  VIRAL_POST_CLICK_CONV: 'Viral Post Click Conversions',
  VIRAL_POST_VIEW_CONV: 'Viral Post View Conversions',
  CONVERSIONS: 'Conversions',
  CLICK_CONVERSIONS: 'Click Conversions',
  VIEW_CONVERSIONS: 'View Conversions',
  CONVERSIONS_RATE: 'Conversions Rate',
  COST_PER_CONVERSION: 'Cost Per Conversion',
  TOTAL_CONVERSIONS_VALUE: 'Total Conversion Value',
  RETURN_ON_AD_SPEND: 'Return on Ad Spend',
  LEADS: 'Leads',
  LEAD_FORM_OPENS: 'Lead Form Opens',
  LEAD_FORM_COMPLETION_RATE: 'Lead Form Completion Rate',
  COST_PER_LEAD: 'Cost Per Lead',
  EVENT_REGISTRATIONS: 'Event Registrations',
  CLICK_EVENT_REGISTRATIONS: 'Click Event Registrations',
  VIEW_EVENT_REGISTRATIONS: 'View Event Registrations',
  VIRAL_EVENT_REGISTRATIONS: 'Virtual Event Registrations',
  VIRAL_CLICK_EVENT_REG: 'Viral Click Event Registrations',
  VIRAL_VIEW_EVENT_REG: 'Viral View Event Registrations',
  VIEWS: 'Views',
  VIEW_RATE: 'View Rate',
  ECVP: 'eCPV',
  VIEW_QUARTILE: 'Views @ 25%',
  VIEW_MIDPOINT: 'Views @ 50%',
  VIEW_THIRD_QUARTILE: 'Views @ 75%',
  COMPLETION_RATE: 'Completion Rate',
  FULL_SCREEN_PLAY: 'Full Screen Plays',
  VIRAL_VIDEO_VIEWS: 'Viral Video Views',
  VIRAL_VIDEO_VIEWS_QUARTILE: 'Viral Video Views @ 25%',
  VIRAL_VIDEO_VIEWS_MIDPOINT: 'Viral Video Views @ 50%',
  VIRAL_VIDEO_VIEWS_THIRD_Q: 'Viral Video Views @ 75%',
  VIRAL_VIDEO_COMPLETIONS: 'Viral Video Completions',
  VIRAL_VIDEO_COMPLETION_RATE: 'Viral Video Completion Rate',
  VIRAL_VIDEO_FULL_SCREEN: 'Viral Video Full Screen Plays',
  COMPLETIONS: 'Completions',
  SENDS: 'Sends',
  OPENS: 'Opens',
  SPONSORED_MESSAGING_CLICKS: 'Sponsored Messaging Clicks',
  BANNER_CLICKS: 'Banner Clicks',
  BUTTON_CLICKS: 'Button Clicks',
  LINK_CLICKS: 'Link Clicks',
  OPEN_RATE: 'Open Rate',
  CLICKS_OPEN_RATE: 'Clicks to Open Rate',
  COST_PER_SEND: 'Cost Per Send',
  COST_PER_OPEN: 'Cost Per Open',
  TALENT_LEADS: 'Talent Leads',
  TALENT_LEAD_RATE: 'Talent Lead Rate',
  COST_PER_TALENT_LEAD: 'Cost Per Talent Lead',
  JOB_APPLY_CLICKS: 'Job Apply Clicks',
  JOB_APPLICATIONS: 'Job Applications',
  JOB_APPLICATION_RATE: 'Job Application Rate',
  COST_PER_JOB_APPLICATION_LEAD: 'Cost Per Job Application Lead',
  CAMPAIGN_GROUP_NAME: 'Campaign Group Name',
  CAMPAIGN_GROUP_ID: 'Campaign Group Id',
  CAMPAIGN_NAME: 'Campaign Name',
  CAMPAIGN_ID: 'Campaign Id',
  AD_NAME: 'Ad Name',
  CREATIVE_ID: 'Creative Id',
}

export default HeaderNames;